name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: oven-sh/setup-bun@v1
        run: bun ci --frozen-lockfile

      - name: Build for production
        run: bun run build
# TODO: Deploy
